apiVersion: v1
kind: Pod
metadata: 
   name: web
spec:
  containers:
  - name: web
    image: nginx
    volumeMounts:
      - mountPath: /mnt/vol
        name: nfs

  volumes:
  - name: nfs
    server: ip-addres-of-nfs-server
    path: "/"
    readOnly: false